### ISSUE TITLE
[Server] Замена StringBuilder

### ISSUE THREAD

**Issue by anry-das** [Andee13/messenger#1]
В коде очень часто встречается кострукция
```
...new StringBuilder("Unable to get property \"clientsDir\" from the configuration")
  .append(config.toString()).toString()
```
Ее можно заменить отдельным методом, формирующим сообщение.

**Comment by birintsev** [comment]
Issue resolving commits : 
https://github.com/Andee13/messenger/commit/58f90a8979bf63865401b813f4e341954acdb00b
https://github.com/Andee13/messenger/commit/0af5f5cec564c9c01731d9e28ec3e22b8c12615d
