### ISSUE TITLE
[Server] Рефакторинг класса ServerProcessing

### ISSUE THREAD

**Issue by anry-das** [Andee13/messenger#2]
Необходимо разнести функционал класса ServerProcessing по разным классам.
Например,
- методы, связанные с обработкой properties, вынести в класс ServerProperties
- методы работы с клиентами / комнатами также вынести в отдельные классы

**Comment by leader228228** [comment]
[This](https://github.com/Andee13/messenger/commit/02c30b1303ebaeb958e5a491f27a198dafaf28ea) is the resolving commit

**Comment by birintsev** [comment]
[This](https://github.com/Andee13/messenger/commit/02c30b1303ebaeb958e5a491f27a198dafaf28ea) is the resolving commit
