### ISSUE TITLE
Server doesn't allow to login for registered user

### ISSUE THREAD

**Issue by Andee13** [Andee13/messenger#3]
![image](https://user-images.githubusercontent.com/39676479/54788797-1d4dde00-4c39-11e9-8b53-fe4a05b983a7.png)

answer message

![image](https://user-images.githubusercontent.com/39676479/54788817-2dfe5400-4c39-11e9-84eb-c16d122472a8.png)

**Comment by birintsev** [comment]
The bug has been fixed at [the commit](https://github.com/Andee13/messenger/commit/d82bacf520d13f9fbee1100c23db9cf0639da957)
