### ISSUE TITLE
Server doesn't allow to enter the chat 

### ISSUE THREAD

**Issue by Andee13** [Andee13/messenger#4]
![image](https://user-images.githubusercontent.com/39676479/54788925-89304680-4c39-11e9-8558-fb568caf9feb.png)

![image](https://user-images.githubusercontent.com/39676479/54788937-93524500-4c39-11e9-99dc-79cc6cc84a4a.png)

The problem can be correlated with "fromid", the client send a message without it

**Comment by birintsev** [comment]
I do not understand what do you mean by saing "enter the chat". Did you want to get the list of client's rooms (ids) and server sent an error message?
